-- Migration: Add Blueprint Implementation Todos Support
-- This extends the agent_blueprints table to support Ami-generated implementation todos

-- Add new fields to agent_blueprints table
ALTER TABLE agent_blueprints 
ADD COLUMN implementation_todos JSONB DEFAULT '[]',
ADD COLUMN todos_completion_status VARCHAR(50) DEFAULT 'not_generated' CHECK (todos_completion_status IN ('not_generated', 'generated', 'in_progress', 'completed')),
ADD COLUMN todos_generated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN todos_generated_by VARCHAR(255),
ADD COLUMN todos_completed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN todos_completed_by VARCHAR(255);

-- Add foreign key constraint for todos_generated_by
ALTER TABLE agent_blueprints 
ADD CONSTRAINT fk_todos_generated_by 
FOREIGN KEY (todos_generated_by) REFERENCES users(id) ON DELETE SET NULL;

-- Add foreign key constraint for todos_completed_by  
ALTER TABLE agent_blueprints 
ADD CONSTRAINT fk_todos_completed_by 
FOREIGN KEY (todos_completed_by) REFERENCES users(id) ON DELETE SET NULL;

-- Update compilation_status check constraint to prevent compilation until todos are completed
ALTER TABLE agent_blueprints 
DROP CONSTRAINT IF EXISTS agent_blueprints_compilation_status_check;

ALTER TABLE agent_blueprints 
ADD CONSTRAINT agent_blueprints_compilation_status_check 
CHECK (compilation_status IN ('draft', 'todos_pending', 'ready_for_compilation', 'compiled', 'failed'));

-- Create index for faster todo queries
CREATE INDEX idx_agent_blueprints_todos_status ON agent_blueprints(todos_completion_status);
CREATE INDEX idx_agent_blueprints_compilation_todos ON agent_blueprints(compilation_status, todos_completion_status);

-- Create function to automatically update todos completion status
CREATE OR REPLACE FUNCTION check_todos_completion()
RETURNS TRIGGER AS $$
BEGIN
    -- If todos are updated, check if all are completed
    IF NEW.implementation_todos IS NOT NULL AND NEW.implementation_todos != OLD.implementation_todos THEN
        -- Check if all todos have status = 'completed'
        IF (
            SELECT COUNT(*) = 0 
            FROM jsonb_array_elements(NEW.implementation_todos) AS todo 
            WHERE (todo->>'status') != 'completed'
        ) AND jsonb_array_length(NEW.implementation_todos) > 0 THEN
            -- All todos completed
            NEW.todos_completion_status = 'completed';
            NEW.todos_completed_at = NOW();
            NEW.compilation_status = 'ready_for_compilation';
        ELSE
            -- Some todos still pending
            NEW.todos_completion_status = 'in_progress';
            NEW.compilation_status = 'todos_pending';
        END IF;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update todos completion status
CREATE TRIGGER trigger_check_todos_completion
    BEFORE UPDATE ON agent_blueprints
    FOR EACH ROW
    EXECUTE FUNCTION check_todos_completion();

COMMENT ON COLUMN agent_blueprints.implementation_todos IS 'JSONB array of todos generated by Ami for blueprint implementation';
COMMENT ON COLUMN agent_blueprints.todos_completion_status IS 'Status of todo completion: not_generated, generated, in_progress, completed';
COMMENT ON COLUMN agent_blueprints.todos_generated_at IS 'When Ami generated the implementation todos';
COMMENT ON COLUMN agent_blueprints.todos_generated_by IS 'User ID who triggered todo generation (usually the blueprint creator)';